apiVersion: v1
entries:
  larping:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-11T08:01:50.6044817Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 85457f8a21defb5d579e16c26a96a260cb6c3dd7b34400a75035bd167d405e05
    home: www.larping.eu
    icon: www.larping.eu
    name: larping
    urls:
    - larping-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-11T08:01:50.6112557Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: c1f66c64f25eee68e386ece411c43f23b2fbc0670e9c625d75cb9178d219e9cd
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2021-01-11T08:01:50.5977522Z"
