apiVersion: v1
entries:
  larping:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-21T11:04:57.4130777Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: cd2b7b8e979d15c6e260d583fd2067ef7678ba3baa6c3e47028e4d6b6431a494
    home: www.larping.eu
    icon: www.larping.eu
    name: larping
    urls:
    - larping-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-21T11:04:57.4233309Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 99e691ac1a2e9bddd3b05f9230f9361b5eadcf8ab73f1d91dcd2edee27bd86df
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-21T11:04:57.403324Z"
