apiVersion: v1
entries:
  larping:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-11T13:53:41.854102Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 21878b370cb493ddb4a5a78d3ca0b43116e3d6324c9173a8b9853c031d33d1ac
    home: www.larping.eu
    icon: www.larping.eu
    name: larping
    urls:
    - larping-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-11T13:53:41.8622947Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 99e691ac1a2e9bddd3b05f9230f9361b5eadcf8ab73f1d91dcd2edee27bd86df
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-11T13:53:41.8450975Z"
