apiVersion: v1
entries:
  larping:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-14T16:28:19.1681081Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 2a29aa7ca5852ce698a463540a1a5ce39c4294726fa2f6d058ff6631f286932f
    home: www.larping.eu
    icon: www.larping.eu
    name: larping
    urls:
    - larping-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-14T16:28:19.1749421Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: c1f66c64f25eee68e386ece411c43f23b2fbc0670e9c625d75cb9178d219e9cd
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2021-01-14T16:28:19.1587118Z"
