apiVersion: v1
entries:
  larping:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-12T08:11:51.4143847Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: d2bbd471f44aacae2abf956cd35d2b957b3b8efca0364ce4bdc694d324cc33b6
    home: www.larping.eu
    icon: www.larping.eu
    name: larping
    urls:
    - larping-0.1.0.tgz
    version: 0.1.0
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-12T08:11:51.4629728Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: c1f66c64f25eee68e386ece411c43f23b2fbc0670e9c625d75cb9178d219e9cd
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2021-01-12T08:11:51.3713114Z"
