apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.settings.name }}-app
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-app
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.settings.name }}-app
    app.kubernetes.io/instance: {{ .Release.Name }}
